server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  application:
    name: order
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.czycwusg477k.ap-northeast-2.rds.amazonaws.com:3306/ordersystem?useSSL=true
    username: root
    password: test1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  redis:
    host: localhost
    port: 6379


jwt:
  expiration: 30
  secretKey: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  expirationRt: 30000
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5



logging:
  level:
    root: info

aws:
  credentials:
    access-key: xxxxxxxx
    secret-key: yyyyyyyy
  region: ap-northeast-2
  s3:
    bucket1: yun-board-profile-image

